DROP TABLE IF EXISTS fato_escalacoes CASCADE;
DROP TABLE IF EXISTS fato_gols CASCADE;
DROP TABLE IF EXISTS dim_jogadores CASCADE;
DROP TABLE IF EXISTS dim_jogos CASCADE;

CREATE TABLE dim_jogos (
    jogo_id                 INTEGER PRIMARY KEY,
    resultado                TEXT,
    corinthians               TEXT,
    gol_cor                  TEXT,
    gol_vis                  INTEGER,
    visitante                 TEXT,
    cidade_visitante          TEXT,
    uf                       TEXT,
    pais                     TEXT,
    dia                      INTEGER,
    mes                      INTEGER,
    ano                      INTEGER,
    hora                     TEXT,
    dia_semana                TEXT,
    campeonato                TEXT,
    capitao                  TEXT,
    tecnico                  TEXT,
    tecnico_visitante          TEXT,
    publico_pagante            NUMERIC,
    renda                    TEXT,
    camisa                   INTEGER,
    saida_de_jogo              TEXT,
    "1_tempo"                 TEXT,
    "2_tempo"                 TEXT,
    artilheiros                TEXT,
    artilheiros_visitante        TEXT,
    num_gols                  INTEGER,
    primeiro_gol               TEXT,
    gol_sul                   INTEGER,
    gol_norte                 INTEGER,
    gol_vis_sul                INTEGER,
    gol_vis_norte              INTEGER,
    gol_1t                    INTEGER,
    gol_2t                    INTEGER,
    gol_vis_1t                 INTEGER,
    gol_vis_2t                 INTEGER,
    arbitro                  TEXT,
    uf_arbitro                 TEXT,
    var                      TEXT,
    data_jogo                 DATE
);

CREATE TABLE dim_jogadores (
    jogador_id               INTEGER PRIMARY KEY,
    jogador                  TEXT,
    posicao                  TEXT,
    jogos                    INTEGER,
    vitorias                  INTEGER,
    empates                  INTEGER,
    derrotas                  INTEGER,
    desempenho                 NUMERIC,
    gols                     NUMERIC,
    assistencias               NUMERIC,
    titular                  INTEGER,
    reserva                  INTEGER,
    substituido               INTEGER,
    capitao                  NUMERIC,
    ca                       INTEGER,
    cv                       NUMERIC,
    brasileiro                INTEGER,
    paulista                  INTEGER,
    copa_do_brasil             NUMERIC,
    libertadores               INTEGER,
    sulamericana               INTEGER,
    amistosos                 NUMERIC,
    gols_norte                 NUMERIC,
    gols_sul                  NUMERIC,
    gols_1_tempo               NUMERIC,
    gols_2_tempo               NUMERIC,
    "2_gols"                  NUMERIC,
    hat_trick                 NUMERIC,
    gols_de_penalti             NUMERIC,
    penaltis_perdidos           NUMERIC,
    gols_de_falta               NUMERIC,
    dentro_da_area              NUMERIC,
    fora_da_area               NUMERIC,
    pe_direito                 NUMERIC,
    pe_esquerdo                NUMERIC,
    cabeca                   NUMERIC,
    gols_contra                NUMERIC,
    gols_outros_estilos          NUMERIC
);

CREATE TABLE fato_gols (
    gol_id                   INTEGER PRIMARY KEY,
    gol_num_original           INTEGER,
    jogo_id                  INTEGER,
    jogador                  TEXT,
    assistencia               TEXT,
    minuto                   TEXT,
    tempo                    TEXT,
    setor                    TEXT,
    area                     TEXT,
    estilo                   TEXT,
    camisa                   TEXT,
    num_camisa                TEXT,
    tit_res                  TEXT,
    res                      TEXT,
    placar                   TEXT,
    adversario                 TEXT,
    campeonato                 TEXT,
    data                     DATE,
    dia_semana                TEXT,
    hora                     TEXT,
    link                     TEXT,
    tipo                     TEXT,
    gol_contra                BOOLEAN
);

CREATE TABLE fato_escalacoes (
    id                       SERIAL PRIMARY KEY,
    jogo_id                  INTEGER,
    jogador                  TEXT,
    papel                    TEXT
);